version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.18.3
    ports:
      - '9000:9000'
    mem_limit: 500m
    mem_reservation: 500m
    volumes:
      - /mnt/c/temp/docker-volumes/portainer/data/portainer_ce:/data
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      USER: admin
      PASSWORD: Pa55w0rd

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_DATABASE=kotlin-rest-api
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
     - '3306:3306'
    volumes:
     - db:/var/lib/mysql

volumes:
  db: