spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kotlin-rest-api?useTimezone=true&serverTimeZone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false